app/apontamento/urls.py
from django.urls import path
from .views import *


app_name = "apontamento"

urlpatterns = [
    path("apontamento-list", apontamento_list, name="apontamento-list"),
    path("folha-ponto", folha_ponto, name="folha-ponto"),
    
]

app/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

app/folha_ponto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("apontamento/", include("apontamento.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/apontamento/models.py
from django.db import models
from django.contrib.auth.models import User


class Ponto(models.Model):
    id = models.IntegerField(
        primary_key=True,
    )
    entrada = models.DateTimeField()
    primeiro = models.BooleanField(default=False)
    segundo = models.BooleanField(default=False)
    atraso = models.BooleanField(default=False)
    saida = models.DateTimeField(null=True, blank=True)
    usuario_id = models.ForeignKey(User, on_delete=models.CASCADE, default=1)
    fechado = models.BooleanField(default=False)
    cliente_id = models.IntegerField(null=True, blank=True)
    tiporeceita_id = models.IntegerField(null=True, blank=True)
    atrasoautorizado = models.BooleanField(default=False)

    class Meta:
        ordering = ("entrada",)

    
    @property
    def difference(self):
        if self.saida is not None:
            return self.saida - self.entrada
        return 0
        
    def __str__(self) -> str:
        return f"{self.usuario_id} {self.entrada} {self.saida} {self.difference}"

app/apontamento/forms.py
from django import forms
from django.contrib.auth.models import User
from apontamento.models import Ponto


class DateInput(forms.DateInput):
    input_type = "date"


class FolhaPontoForm(forms.Form):
    entrada = forms.DateField(widget=DateInput, label="Início", required=False)
    saida = forms.DateField(widget=DateInput, label="Fim", required=False)
    usuario = forms.ModelChoiceField(queryset=User.objects.all(), required=False)

app/apontamento/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from apontamento.services import PontoService
from apontamento.forms import FolhaPontoForm
from apontamento.models import Ponto

from datetime import datetime, timedelta
from django.db.models import Avg, Count, Min, Sum

@login_required
def apontamento_list(request, login_url="users:login"):
    return render(request, "apontamento/apontamento-list.html", {})


def folha_ponto(request):        
    usuario = User.objects.filter(username="sara").first()
    service = PontoService()
    pontos = service.ponto_list(
        usuario.id,
        data_inicial=datetime(2023, 9, 1, 0, 0, 0).date(),
        data_final=datetime(2023, 9, 2, 0, 0, 0).date(),
    )

    pontos_sumarizados = []
    diferenca = timedelta(0)
    for ponto in pontos:
        dia = ponto.entrada.date()
        if ponto.entrada.date() == dia:
            diferenca += ponto.saida - ponto.entrada
        else:
            diferenca = timedelta(0)
            pontos_sumarizados.append(dia, diferenca)


    nome = usuario.username
    context = {"pontos_sumarizados": pontos_sumarizados, "nome": nome}


    return render(
        request,
        "apontamento/folha-ponto.html",
        context,
    )

app/apontamento/templates/apontamento/apontamento-list.html
{% extends 'base.html' %} 
{% block title %} Folha de Ponto | {{object.title}} 
{% endblock title %} {% load static %} 

{% block content %}

<section class="py-5">
  <div class="container px-4 px-lg-5 mt-5">
    <div
      class="row gx-4 gx-lg-5 row-cols-2 row-cols-md-3 row-cols-xl-4 justify-content-center"
    >
      <h1>Apontamento</h1>
    </div>
  </div>
</section>

{% endblock %}

app/apontamento/templates/apontamento/folha-ponto-backup.html
{% extends "base.html" %} {% load crispy_forms_tags %} {% load static %} 

{%block content %}
<div class="container border border-dark">
  <h1>Folha Ponto</h1>

  <form method="post" enctype="multipart/form-data">
    {% csrf_token %}

    <div class="row">
      <div class="col-md-4">{{form.entrada|as_crispy_field}}</div>
      <div class="col-md-4">{{form.saida|as_crispy_field}}</div>
      <div class="col-md-4">{{form.usuario|as_crispy_field}}</div>
    </div>
    <div class="text-center mb-3">
      <div
        class="btn-group btn-group-lg"
        role="group"
        aria-label="Basic example"
      >
        <a
          href="{% url 'apontamento:folha-ponto' %}"
          class="btn btn-primary btn-block btn-lg"
        >
          <i class="fa-solid fa-search"></i> Consulta
        </a>
        <button type="button" class="btn btn-warning">
          <i class="fa-solid fa-file-excel"></i> Exportar
        </button>
        <button type="button" class="btn btn-primary">
          <i class="fa-solid fa-arrows-rotate"></i> Limpar
        </button>
      </div>
    </div>
  </form>
</div>
<div class="container border border-dark">
  <h4>Resultado da Consulta</h4>
  <table class="table table-striped">
    <thead>
      <tr></tr>
    </thead>
    <tbody>
      <tr>
        <td colspan="4">
          <table class="table mb-0">
            <thead>
              <tr>
                <th></th>
                <th>Data</th>
                <th>Atrasado</th>
                <th>Trabalhadas</th>
                <th>Credor</th>
                <th>Devedor</th>
              </tr>
            </thead>
            <tbody>
              {% for ponto in pontos %}
              <tr>
                <td><i class="fa-solid fa-pencil"></i></td>
                <td>{{ponto.entrada.atraso}}</td>
                <td>{{ponto.entrada.time|time:"H:i"}}</td>
                <td>{{ponto.saida.time}}</td>
              </tr>
              {% endfor %}
            </tbody>
          </table>
        </td>
      </tr>
    </tbody>
  </table>
</div>
{% endblock %}

app/apontamento/templates/apontamento/folha-ponto.html
{{ pontos_sumarizados }}