app/core/urls.py
from django.urls import path
from .views import *

app_name = "core"

urlpatterns = [
    path("", home, name="home"),
]

app/folha_ponto/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("core.urls")),
    path("apontamento/", include("apontamento.urls")),
    path("users/", include("users.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

app/users/urls.py
from django.urls import path
from .views import NewLoginView, logout_view

app_name = "users"

urlpatterns = [
    path("login/", NewLoginView.as_view(), name="login"),
    path("logout/", logout_view, name="logout"),
]

app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    {% load django_bootstrap5 %} 
    {% bootstrap_css %} 
    
    {{ form.media }}
    {% bootstrap_messages %} 
    {% load crispy_forms_tags %}

    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <script src="/static/smart-selects/admin/js/chainedfk.js"></script>
    <script src="/static/smart-selects/admin/js/bindfields.js"></script>

    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>{% block title %} {% endblock title %}</title>
    <!-- Favicon-->
    <link rel="icon" type="image/x-icon" href="assets/favicon.ico" />
    <!-- Bootstrap icons-->
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.5.0/font/bootstrap-icons.css"
      rel="stylesheet"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/login.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" type="text/css">

    <!-- Our project just needs Font Awesome Free's Solid and Brand files -->
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">

  </head>
  <body>
    <!-- Navigation-->
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container px-4 px-lg-5">
        <a class="navbar-brand" href="#!">BV Contabilidade</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="#">Home</a>
            </li>
            <li class="nav-item"><a class="nav-link" href="#!">About</a></li>
            {% if request.user.is_authenticated %}
            <a href="{% url 'users:logout' %}" class="btn btn-outline"
              >Logout</a
            >
            {% else %}
            <a href="{% url 'users:login' %}" class="btn btn-outline">Login</a>

            {% endif %}
            <li></li>
          </ul>
        </div>
      </div>
    </nav>
    <!-- Header-->
    <!--<header class="bg-dark py-5">
      <div class="container px-4 px-lg-5 my-5">
        <div class="text-center text-white">
          <h1 class="display-4 fw-bolder">Shop in style</h1>
          <p class="lead fw-normal text-white-50 mb-0">
            With this shop hompeage template
          </p>
        </div>
      </div>
    </header>-->
    <!-- Section-->
    <div class="container mt-5">
          {% block content %} 
          
          {% endblock %}
    </div>
    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{% static 'js/scripts.js' %}"></script>
  </body>
</html>